USE crm_incihuila;


-- Tabla: roles
CREATE TABLE roles (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(90) NOT NULL UNIQUE,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla: users
CREATE TABLE users (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    rol_id BIGINT NOT NULL,
    correo VARCHAR(90) NOT NULL UNIQUE,
    first_name VARCHAR(90) NOT NULL,
    second_name VARCHAR(90) NULL,
    last_name VARCHAR(90) NOT NULL,
    phone VARCHAR(90) NOT NULL UNIQUE,
    age INT NOT NULL,
    password VARCHAR(90) NOT NULL,
    estado ENUM('activo', 'no activo') DEFAULT 'activo',
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (rol_id) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE products (
	name VARCHAR(180) NOT NULL,
    stocks INT NOT NULL,
    price FLOAT NOT NULL,
    description TEXT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabla: agendas
CREATE TABLE agendas (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(180) NOT NULL,
    fecha DATE NOT NULL,
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);